version: "3"
services:
  web_vang:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3000:3000"
    volumes: 
      - ./vang:/opt/app
      - gem_cache_vang:/gems
    env_file: 
      - .env/development/database_vang
      - .env/development/web_vang
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_vang
    networks:
      - network
  webpack_dev_server_vang:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3035:3035"
    volumes: 
      - ./vang:/opt/app
      - gem_cache_vang:/gems
    env_file: 
      - .env/development/database_vang
      - .env/development/web_vang
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_vang:
    image: postgres
    env_file: 
      - .env/development/database_vang
    volumes: 
      - db_data_vang:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_vang:
  gem_cache_vang:
networks:
  network: