source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.3.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# A modern CSS framework based on Flexbox
gem 'bulma-rails', '~> 0.8.2' #([<https://rubygems.org/gems/bulma-rails>](<https://rubygems.org/gems/bulma-rails>))
# Forms made easy!
gem 'simple_form', '~> 5.0', '>= 5.0.2' #([<https://rubygems.org/gems/simple_form>](<https://rubygems.org/gems/simple_form>))
# A configurable and documented Rails view helper for adding gravatars into your Rails application.
gem 'gravatar_image_tag', '~> 1.2' #([<https://rubygems.org/gems/gravatar_image_tag>](<https://rubygems.org/gems/gravatar_image_tag>))
# Flexible authentication solution for Rails with Warden
gem 'devise', '~> 4.7', '>= 4.7.1' #([<https://rubygems.org/gems/devise>](<https://rubygems.org/gems/devise>))
#Upload files in your Ruby applications, map them to a range of ORMs, store them on different backends.
gem 'carrierwave', '~> 1.2', '>= 1.2.1' #([<https://rubygems.org/gems/carrierwave>](<https://rubygems.org/gems/carrierwave>))
#Manipulate images with minimal use of memory via ImageMagick / GraphicsMagick
gem 'mini_magick', '~> 4.10', '>= 4.10.1' #([<https://rubygems.org/gems/mini_magick>](<https://rubygems.org/gems/mini_magick>))
#Log impressions from controller actions or from a model
gem 'impressionist', '~> 2.0' #([<https://rubygems.org/gems/impressionist>](<https://rubygems.org/gems/impressionist>))
#This gem provides jQuery and the jQuery-ujs driver for your Rails 4+ application.
gem 'jquery-rails', '~> 4.4' #([<https://rubygems.org/gems/jquery-rails>](<https://rubygems.org/gems/jquery-rails>))
#Rails gem to allowing records to be votable
gem 'acts_as_votable', '~> 0.12.1' #([<https://rubygems.org/gems/acts_as_votable>](<https://rubygems.org/gems/acts_as_votable>))

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
